### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by skalerr** [justindannguyen/sw-bot#15]
I am trying to run the distribution via mvnw.cmd but it does not start with an error "build faulture"
![2019-01-08 15 42 53](https://user-images.githubusercontent.com/46483879/50826569-cdf85100-135d-11e9-8612-5e6ed4f7b24c.png)
Installed
 apache-maven-3.6.0
 javacv-1.3.3
 jdk-11.0.1
 adb
(Android connected via adb with running sw)
Device Xiaomi mi a1

Could you help me

**Comment by justindannguyen** [comment]
Look like you run maven cmd incorrectly.
Try again with `mvn clean install`.

Another easier appoach for you: download java eclipse at [link](https://www.eclipse.org/downloads/packages/) then import project into eclipse as Maven project. Finally run `Main.java`

**Comment by skalerr** [comment]
Thx
